### ISSUE TITLE
This patch is not intended for this rom

### ISSUE THREAD

**Issue by TsukiZero** [Lorenzooone/M3_Text_Skipping#1]
Even on clean, japanese dumps.

**Comment by Lorenzooone** [comment]
To be clear, for the Japanese version, are you using the patches which end with "_j"?

I just tried those, to be sure, and they work for me...

**Comment by TsukiZero** [comment]
Found out the cause: My patcher tool doesn't like the patch, so had to use the batch one included here rather than the BPS TCRF provides.

**Comment by Lorenzooone** [comment]
Hmm... You could try using the online one. https://www.marcrobledo.com/RomPatcher.js/
Otherwise, NUPS will work fine as an executable.
Regardless of that, closing this for now.

**Comment by TsukiZero** [comment]
Agreed, thanks.
